INSERT INTO products (name, description, original_price, image_url, status) VALUES
('Neuro-Link Pro v4', 'Neural interface for ultra-low latency direct data streaming.', 12999.00, 'local:phone', 1),
('Cybernetic Arm Mk.II', 'Industrial grade prosthetic with integrated plasma torch.', 45000.00, 'local:box', 1),
('Onyx Workstation', 'Quantum-cooled desktop for massive parallel simulation.', 89999.00, 'local:laptop', 1),
('Thermal Sight Visor', 'Tactical head-up display with multi-spectrum analysis.', 3499.00, 'local:audio', 1),
('Data-Shard 2TB', 'High-speed physical storage for encrypted protocol logs.', 899.00, 'local:box', 1),
('Protocol-Z Bypass', 'Software bypass for standard security checkpoints.', 1500.00, 'local:box', 1),
('Viper GPU X-100', 'Teraflop-scale graphics accelerator for real-time rendering.', 12000.00, 'local:laptop', 1),
('Stealth Cloak Skin', 'Light-bending wearable fabric for visual obfuscation.', 5600.00, 'local:audio', 1),
('Bio-Monitor Patch', 'Sub-dermal sensor for real-time health data uplink.', 299.00, 'local:phone', 1),
('Edge-Node Router', 'Distributed networking hub for zero-latency trading.', 4500.00, 'local:box', 1),
('Titan Power-Cell', 'High-density battery for cybernetic enhancements.', 1200.00, 'local:box', 1),
('Void-Ear Headset', 'Zero-leak auditory immersion with neural isolation.', 3200.00, 'local:audio', 1),
('Matrix-Key Deck', 'Holographic input interface for rapid code deployment.', 2100.00, 'local:laptop', 1),
('Signal Jammer Mini', 'Pocket-sized RF interference device for privacy.', 750.00, 'local:phone', 1),
('Glitch-Core CPU', 'Processor optimized for non-linear logic execution.', 7800.00, 'local:laptop', 1),
('Neon-Cycle Frame', 'Ultra-light carbon frame for high-speed transit.', 15000.00, 'local:box', 1),
('Tactical Glove v2', 'Haptic feedback gloves with integrated NFC hacking tool.', 1800.00, 'local:box', 1),
('Plasma Blade XP', 'Condensed energy blade for rapid asset liquidation.', 22000.00, 'local:box', 1),
('Shadow-Step Boots', 'Sound-dampening footwear for silent operation.', 2400.00, 'local:box', 1),
('Cyber-Eye Mk.III', 'Optical replacement with 100x zoom and night vision.', 9500.00, 'local:phone', 1),
('Encrypted Comms Unit', 'Direct satellite uplink with 4096-bit encryption.', 5500.00, 'local:phone', 1),
('Hydra Server Rack', 'Multi-tenant high-availability compute cluster.', 120000.00, 'local:box', 1),
('Pulse-Grenade (Mock)', 'Non-lethal EMP simulator for system testing.', 450.00, 'local:box', 1),
('Neural-Imprint Kit', 'Backup and recovery kit for digital consciousness.', 35000.00, 'local:box', 1),
('Carbon-Fiber Mask', 'Lightweight respirator for hazardous environments.', 1100.00, 'local:box', 1),
('Nano-Repair Paste', 'Instant hardware fix for minor shell damage.', 350.00, 'local:box', 1),
('Protocol-Zero Chip', 'Specialized silicon for zero-knowledge proofs.', 8900.00, 'local:phone', 1),
('Sub-Grid Mapper', 'Real-time topological scanner for dark-net nodes.', 6700.00, 'local:laptop', 1),
('Sonic-Pulse Audio', 'Sound-wave based defense and analysis tool.', 4200.00, 'local:audio', 1),
('Liquid-Metal Paste', 'Ultra-high conductivity thermal interface material.', 150.00, 'local:box', 1),
('Drone-Controller Kit', 'Long-range control uplink for autonomous scouts.', 3200.00, 'local:laptop', 1),
('Bio-Metric Scrambler', 'Device to generate fake physiological signatures.', 2800.00, 'local:phone', 1),
('Augmented Reality Glasses', 'Overlay digital data onto physical reality.', 4500.00, 'local:phone', 1),
('Smart-Contract Hub', 'Hardware wallet for secure protocol execution.', 1200.00, 'local:box', 1),
('Fiber-Optic Cable 10km', 'Ultra-fast physical connection for data centers.', 5000.00, 'local:box', 1),
('Quantum-Crypto Key', 'Disposable keys for unbreakable data transit.', 999.00, 'local:box', 1),
('Heat-Shield Blanket', 'Protection for sensitive hardware during fire.', 600.00, 'local:box', 1),
('Micro-Soldering Pen', 'Precision tool for delicate circuit repairs.', 250.00, 'local:box', 1),
('Static-Guard Spray', 'Prevents electrical damage in dry environments.', 80.00, 'local:box', 1),
('Universal Logic Gate', 'Programmable gate array for custom hardware.', 1400.00, 'local:box', 1),
('Satellite-Dish Pro', 'High-gain antenna for remote uplink access.', 8500.00, 'local:box', 1),
('Encrypted Journal', 'Physical book with chemical self-destruct ink.', 320.00, 'local:box', 1),
('Neural-Stress Monitor', 'Tracks user cognitive load during rush events.', 1600.00, 'local:phone', 1),
('Emergency Kill-Switch', 'Physical interrupter for critical system failure.', 500.00, 'local:box', 1),
('High-Torque Cyber-Hand', 'Replacement hand optimized for physical labor.', 18000.00, 'local:box', 1),
('Radar-Absorbent Paint', 'Special coating to reduce electronic signature.', 2200.00, 'local:box', 1),
('Mini-Fusion Cell', 'Long-life power source for portable consoles.', 4500.00, 'local:box', 1),
('Neural-Link Cable', 'Direct physical interface for older hardware.', 180.00, 'local:box', 1),
('Encrypted-Voice Mic', 'Hardware-level voice masking for clear comms.', 950.00, 'local:audio', 1),
('Digital-Hazmat Suit', 'Full body protection for radiation and logic bombs.', 15000.00, 'local:box', 1);