<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import { createProduct, createFlashSale } from '@/api/admin'
import { getProducts } from '@/api/product'
import type { Product } from '@/types'
import { Loader2, Plus, Package, Zap, RefreshCw, Upload, Sparkles, BrainCircuit } from 'lucide-vue-next'

const activeTab = ref<'product' | 'flash_sale'>('product')
const products = ref<Product[]>([])
const loading = ref(false)
const generatingAI = ref(false)
const generatingFlashAI = ref(false)
const message = ref('')
const messageType = ref<'success' | 'error'>('success')

const generateAIContent = async () => {
  if (!productForm.value.name) {
    showMessage('Please enter a product name first', 'error')
    return
  }
  generatingAI.value = true
  try {
    await new Promise(resolve => setTimeout(resolve, 1200))
    const name = productForm.value.name.toLowerCase()
    let desc = `High-performance asset: ${productForm.value.name}. Optimized for low-latency environments.`
    let price = 499.00
    if (name.includes('phone')) {
      desc = `Next-gen mobile node with neural processing units. The ${productForm.value.name} features an adaptive 144Hz OLED and quantum-dot imaging.`
      price = 6999.00
    } else if (name.includes('laptop') || name.includes('mac')) {
      desc = `Ultra-dense computing workstation. Powered by a 16-core liquid-cooled processor, the ${productForm.value.name} is built for massive parallel workloads.`
      price = 15999.00
    } else if (name.includes('headphone') || name.includes('audio') || name.includes('pod')) {
      desc = `Zero-latency auditory interface. Features active neural noise cancellation and high-fidelity spatial awareness.`
      price = 2499.00
    } else if (name.includes('gpu') || name.includes('card')) {
      desc = `Teraflop-scale graphics accelerator. The ultimate hardware for real-time ray tracing and complex simulation rendering.`
      price = 8999.00
    }
    productForm.value.description = desc
    productForm.value.original_price = price
    showMessage('Metadata generated by AI', 'success')
  } catch (e) {
    showMessage('AI link failed', 'error')
  } finally {
    generatingAI.value = false
  }
}

const generateFlashAI = async () => {
  if (flashSaleForm.value.product_id === 0) {
    showMessage('Select a base product first', 'error')
    return
  }
  generatingFlashAI.value = true
  try {
    await new Promise(resolve => setTimeout(resolve, 1000))
    const selectedProd = products.value.find(p => p.id === flashSaleForm.value.product_id)
    if (selectedProd) {
      flashSaleForm.value.flash_price = Math.round(selectedProd.original_price * 0.01 * 100) / 100 || 0.01
      flashSaleForm.value.total_stock = Math.floor(Math.random() * 50) + 10
      const now = new Date()
      now.setMinutes(now.getMinutes() + 5)
      flashSaleForm.value.start_time = new Date(now.getTime() - now.getTimezoneOffset() * 60000).toISOString().slice(0, 16)
      now.setHours(now.getHours() + 1)
      flashSaleForm.value.end_time = new Date(now.getTime() - now.getTimezoneOffset() * 60000).toISOString().slice(0, 16)
      showMessage('Optimized flash parameters set', 'success')
    }
  } finally {
    generatingFlashAI.value = false
  }
}

const assetTypes = [
  { id: 'phone', label: 'Phone', icon: '📱' },
  { id: 'laptop', label: 'Laptop', icon: '💻' },
  { id: 'audio', label: 'Audio', icon: '🎧' },
  { id: 'box', label: 'Other', icon: '📦' },
]

const productForm = ref({
  name: '',
  description: '',
  original_price: 0,
  image_url: ''
})

const flashSaleForm = ref({
  product_id: 0,
  flash_price: 0,
  total_stock: 100,
  per_user_limit: 1,
  start_time: '',
  end_time: ''
})

const showMessage = (msg: string, type: 'success' | 'error') => {
  message.value = msg
  messageType.value = type
  setTimeout(() => message.value = '', 4000)
}

const handleImageUpload = (event: Event) => {
  const input = event.target as HTMLInputElement
  if (input.files && input.files[0]) {
    const file = input.files[0]
    if (file.size > 2 * 1024 * 1024) {
      showMessage('Object too dense. Max 2MB allowed.', 'error')
      return
    }
    const reader = new FileReader()
    reader.onload = (e) => {
      const img = new Image()
      img.onload = () => {
        const canvas = document.createElement('canvas')
        let width = img.width
        let height = img.height
        const maxSide = 1024
        if (width > maxSide || height > maxSide) {
          if (width > height) {
            height = (height / width) * maxSide
            width = maxSide
          } else {
            width = (width / height) * maxSide
            height = maxSide
          }
        }
        canvas.width = width
        canvas.height = height
        const ctx = canvas.getContext('2d')
        ctx?.drawImage(img, 0, 0, width, height)
        productForm.value.image_url = canvas.toDataURL('image/jpeg', 0.8)
      }
      img.src = e.target?.result as string
    }
    reader.readAsDataURL(file)
  }
}

const handleCreateProduct = async () => {
  if (!productForm.value.image_url) {
    showMessage('Visual asset required', 'error')
    return
  }
  loading.value = true
  try {
    const res = await createProduct(productForm.value)
    if (res.code === 0) {
      showMessage(`Registry Entry Created: ID ${res.data.id}`, 'success')
      flashSaleForm.value.product_id = res.data.id
      const prevImg = productForm.value.image_url
      productForm.value = { name: '', description: '', original_price: 0, image_url: prevImg }
    } else {
      showMessage(res.message, 'error')
    }
  } catch (e: any) {
    showMessage(e.response?.data?.message || 'Uplink Failed', 'error')
  } finally {
    loading.value = false
  }
}

const fetchProducts = async () => {
  try {
    const res = await getProducts(1, 200)
    if (res.code === 0) products.value = res.data.products
  } catch (e) {}
}

watch(activeTab, (val) => {
  if (val === 'flash_sale') fetchProducts()
})

onMounted(() => fetchProducts())

const handleCreateFlashSale = async () => {
  loading.value = true
  try {
    const payload = {
      ...flashSaleForm.value,
      start_time: new Date(flashSaleForm.value.start_time).toISOString(),
      end_time: new Date(flashSaleForm.value.end_time).toISOString()
    }
    const res = await createFlashSale(payload)
    if (res.code === 0) {
      showMessage(`Flash Event Synchronized: ID ${res.data.id}`, 'success')
    } else {
      showMessage(res.message, 'error')
    }
  } catch (e: any) {
    showMessage(e.response?.data?.message || 'Sync Failed', 'error')
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="min-h-screen pb-20 bg-background text-primary selection:bg-accent selection:text-white">
    <div class="py-16 px-6 md:px-12 border-b border-white/5 mb-12 bg-black/40 backdrop-blur-md">
      <div class="container mx-auto">
        <div class="flex items-center gap-4 mb-4">
          <div class="w-2 h-8 bg-accent animate-pulse"></div>
          <h1 class="text-5xl md:text-6xl font-black tracking-tighter text-white uppercase">Merchant <span class="text-accent">Console</span></h1>
        </div>
        <p class="text-secondary text-xs font-mono tracking-[0.4em] uppercase opacity-60">System Registry // Administrative Uplink v4.0.1</p>
      </div>
    </div>

    <div class="container mx-auto px-6 md:px-12 grid grid-cols-1 lg:grid-cols-4 gap-12">
      <div class="space-y-4">
        <button 
          @click="activeTab = 'product'"
          :class="[
            'w-full text-left px-6 py-4 text-xs font-black uppercase tracking-[0.2em] transition-all border flex items-center gap-4',
            activeTab === 'product' ? 'border-accent bg-accent/5 text-white shadow-[0_0_20px_rgba(227,53,53,0.2)]' : 'border-white/5 text-secondary hover:text-white hover:border-white/20'
          ]"
        >
          <Package :class="['w-5 h-5', activeTab === 'product' ? 'text-accent' : 'text-tertiary']" />
          Asset Creation
        </button>
        <button 
          @click="activeTab = 'flash_sale'"
          :class="[
            'w-full text-left px-6 py-4 text-xs font-black uppercase tracking-[0.2em] transition-all border flex items-center gap-4',
            activeTab === 'flash_sale' ? 'border-accent bg-accent/5 text-white shadow-[0_0_20px_rgba(227,53,53,0.2)]' : 'border-white/5 text-secondary hover:text-white hover:border-white/20'
          ]"
        >
          <Zap :class="['w-5 h-5', activeTab === 'flash_sale' ? 'text-accent' : 'text-tertiary']" />
          Event Sync
        </button>
        
        <div class="mt-20 p-6 bg-white/5 border border-white/5 rounded-sm">
          <div class="flex items-center gap-2 mb-4 text-accent">
            <BrainCircuit class="w-4 h-4" />
            <span class="text-[10px] font-black uppercase tracking-widest">AI Status</span>
          </div>
          <p class="text-[10px] text-tertiary leading-relaxed uppercase font-mono">Neural network standby. Ready to optimize metadata and event parameters.</p>
        </div>
      </div>

      <div class="lg:col-span-3">
        <transition name="fade" mode="out-in">
          <div v-if="message" :class="[
            'mb-8 p-5 text-xs font-mono font-bold tracking-widest border-l-4 shadow-xl',
            messageType === 'success' ? 'bg-green-500/10 text-green-400 border-green-500' : 'bg-red-500/10 text-red-400 border-red-500'
          ]">
            [SYSTEM_LOG] > {{ message }}
          </div>
        </transition>

        <form v-if="activeTab === 'product'" @submit.prevent="handleCreateProduct" class="space-y-8 bg-white/5 p-10 border border-white/5">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div class="space-y-6">
              <div class="space-y-2">
                <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]">Entry Identity (Name)</label>
                <input v-model="productForm.name" type="text" required class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono text-sm tracking-tight" />
              </div>
              
              <div class="space-y-2">
                <div class="flex justify-between items-center">
                  <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]">Functional Specs</label>
                  <button type="button" @click="generateAIContent" class="text-[10px] text-accent hover:text-white flex items-center gap-2 transition-all font-black uppercase tracking-widest" :disabled="generatingAI">
                    <Sparkles class="w-3 h-3" /> {{ generatingAI ? 'Processing...' : 'Neural Auto-Fill' }}
                  </button>
                </div>
                <textarea v-model="productForm.description" rows="4" class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono text-xs leading-relaxed"></textarea>
              </div>

              <div class="space-y-2">
                <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]">Original Value (¥)</label>
                <input v-model.number="productForm.original_price" type="number" step="0.01" required class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono" />
              </div>
            </div>

            <div class="space-y-6">
              <div class="space-y-2">
                <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]">Visual Component</label>
                <div class="grid grid-cols-2 gap-2 mb-4">
                  <button
                    v-for="type in assetTypes"
                    :key="type.id"
                    type="button"
                    @click="productForm.image_url = `local:${type.id}`"
                    :class="[
                      'py-3 border text-[10px] font-black uppercase tracking-widest transition-all flex items-center justify-center gap-2',
                      productForm.image_url === `local:${type.id}` ? 'bg-accent text-white border-accent' : 'bg-black/40 border-white/10 text-tertiary hover:border-white/30'
                    ]"
                  >
                    <span>{{ type.icon }}</span> <span>{{ type.label }}</span>
                  </button>
                </div>

                <label class="block cursor-pointer group">
                  <div class="flex flex-col items-center justify-center gap-3 py-10 border border-dashed border-white/10 group-hover:border-accent/50 transition-all bg-black/20">
                    <Upload class="w-6 h-6 text-tertiary group-hover:text-accent transition-colors" />
                    <span class="text-[10px] text-tertiary font-black uppercase tracking-widest">Uplink Raw Image</span>
                  </div>
                  <input type="file" accept="image/*" @change="handleImageUpload" class="hidden" />
                </label>

                <div class="pt-4">
                  <input v-model="productForm.image_url" type="text" placeholder="REMOTE_URL_HASH..." class="w-full bg-black border border-white/10 px-4 py-3 text-white focus:border-accent outline-none font-mono text-[10px] tracking-tighter overflow-hidden" />
                </div>
              </div>
            </div>
          </div>

          <button type="submit" :disabled="loading" class="w-full h-16 bg-white text-black font-black uppercase tracking-[0.3em] hover:bg-accent hover:text-white transition-all flex items-center justify-center gap-4 text-lg">
            <Loader2 v-if="loading" class="w-6 h-6 animate-spin" />
            <Plus v-else class="w-6 h-6" />
            Commit to Registry
          </button>
        </form>

        <form v-if="activeTab === 'flash_sale'" @submit.prevent="handleCreateFlashSale" class="space-y-8 bg-white/5 p-10 border border-white/5">
          <div class="space-y-6">
            <div class="space-y-2">
              <div class="flex justify-between items-center">
                <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]">Target Asset</label>
                <button type="button" @click="fetchProducts" class="text-[10px] text-accent hover:text-white flex items-center gap-2 transition-all font-black uppercase tracking-widest">
                  <RefreshCw class="w-3 h-3" /> Re-sync List
                </button>
              </div>
              <div class="relative">
                <select v-model.number="flashSaleForm.product_id" required class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none appearance-none cursor-pointer font-mono text-sm">
                  <option :value="0" disabled>NULL_SELECTION</option>
                  <option v-for="p in products" :key="p.id" :value="p.id">ID:{{ p.id }} // {{ p.name }} (Original: ¥{{ p.original_price }})</option>
                </select>
                <div class="absolute right-6 top-1/2 -translate-y-1/2 pointer-events-none text-accent text-xs">▼</div>
              </div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-8 items-start">
               <div class="space-y-6">
                  <div class="space-y-2">
                    <div class="flex justify-between items-center">
                      <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]">Flash Value (¥)</label>
                      <button type="button" @click="generateFlashAI" class="text-[10px] text-accent hover:text-white flex items-center gap-2 transition-all font-black uppercase tracking-widest" :disabled="generatingFlashAI">
                        <Sparkles class="w-3 h-3" /> Neural Optimization
                      </button>
                    </div>
                    <input v-model.number="flashSaleForm.flash_price" type="number" step="0.01" required class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono" />
                  </div>
                  <div class="space-y-2">
                    <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]">Unit Capacity</label>
                    <input v-model.number="flashSaleForm.total_stock" type="number" required class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono" />
                  </div>
               </div>
               
               <div class="space-y-6">
                  <div class="space-y-2">
                    <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]">Timeline Initial</label>
                    <input v-model="flashSaleForm.start_time" type="datetime-local" required class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono text-sm" />
                  </div>
                  <div class="space-y-2">
                    <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]">Timeline Termination</label>
                    <input v-model="flashSaleForm.end_time" type="datetime-local" required class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono text-sm" />
                  </div>
               </div>
            </div>

            <div class="space-y-2">
              <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]">Entity Acquisition Limit</label>
              <input v-model.number="flashSaleForm.per_user_limit" type="number" min="1" required class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono" />
            </div>
          </div>

          <button type="submit" :disabled="loading" class="w-full h-16 bg-accent text-white font-black uppercase tracking-[0.3em] hover:bg-white hover:text-black transition-all flex items-center justify-center gap-4 text-lg">
            <Loader2 v-if="loading" class="w-6 h-6 animate-spin" />
            <Zap v-else class="w-6 h-6" />
            Synchronize Flash Event
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

<style scoped>
.fade-enter-active, .fade-leave-active { transition: opacity 0.4s ease; }
.fade-enter-from, .fade-leave-to { opacity: 0; }
input::-webkit-calendar-picker-indicator { filter: invert(1); cursor: pointer; }
</style>