<script setup lang="ts">
import { ref, watch, onMounted, computed } from 'vue'
import { createProduct, createFlashSale } from '@/api/admin'
import { uploadImage } from '@/api/upload'
import { getProducts } from '@/api/product'
import { sendChatMessage } from '@/api/ai'
import type { Product } from '@/types'
import {
  Loader2,
  Plus,
  Package,
  Zap,
  RefreshCw,
  Upload,
  Sparkles,
  BrainCircuit,
  X,
  Search,
} from 'lucide-vue-next'

const activeTab = ref<'product' | 'flash_sale'>('product')
const products = ref<Product[]>([])
const loading = ref(false)
const generatingAI = ref(false)
const generatingFlashAI = ref(false)
const message = ref('')
const messageType = ref<'success' | 'error'>('success')
const uploadingImage = ref(false)

const showProductModal = ref(false)
const productSearchQuery = ref('')
const aiLogs = ref<string[]>([])

const addAILog = (log: string) => {
  aiLogs.value.push(`[${new Date().toLocaleTimeString()}] ${log}`)
}

const sortedProducts = computed(() => {
  return [...products.value].sort((a, b) => a.id - b.id)
})

const filteredProducts = computed(() => {
  if (!productSearchQuery.value) return sortedProducts.value
  const q = productSearchQuery.value.toLowerCase()
  return sortedProducts.value.filter(
    (p) => p.name.toLowerCase().includes(q) || p.id.toString().includes(q)
  )
})

const selectedProduct = computed(() => {
  return products.value.find((p) => p.id === flashSaleForm.value.product_id)
})

const selectProduct = (p: Product) => {
  flashSaleForm.value.product_id = p.id
  showProductModal.value = false
  productSearchQuery.value = ''
}

const generateAIContent = async () => {
  if (!productForm.value.name) {
    showMessage('Please enter a product name first', 'error')
    return
  }
  generatingAI.value = true
  try {
    await new Promise((resolve) => setTimeout(resolve, 1200))
    const name = productForm.value.name.toLowerCase()
    let desc = `High-performance asset: ${productForm.value.name}. Optimized for low-latency environments.`
    let price = 499.0
    if (name.includes('phone')) {
      desc = `Next-gen mobile node with neural processing units. The ${productForm.value.name} features an adaptive 144Hz OLED and quantum-dot imaging.`
      price = 6999.0
    } else if (name.includes('laptop') || name.includes('mac')) {
      desc = `Ultra-dense computing workstation. Powered by a 16-core liquid-cooled processor, the ${productForm.value.name} is built for massive parallel workloads.`
      price = 15999.0
    } else if (name.includes('headphone') || name.includes('audio') || name.includes('pod')) {
      desc = `Zero-latency auditory interface. Features active neural noise cancellation and high-fidelity spatial awareness.`
      price = 2499.0
    } else if (name.includes('gpu') || name.includes('card')) {
      desc = `Teraflop-scale graphics accelerator. The ultimate hardware for real-time ray tracing and complex simulation rendering.`
      price = 8999.0
    }
    productForm.value.description = desc
    productForm.value.original_price = price
    showMessage('Metadata generated by AI', 'success')
  } catch {
    showMessage('AI link failed', 'error')
  } finally {
    generatingAI.value = false
  }
}

const generateFlashAI = async () => {
  if (flashSaleForm.value.product_id === 0) {
    showMessage('Select a base product first', 'error')
    return
  }
  const selectedProd = products.value.find((p) => p.id === flashSaleForm.value.product_id)
  if (!selectedProd) return

  aiLogs.value = []
  generatingFlashAI.value = true

  try {
    addAILog('INIT: Neural link established')
    addAILog(`TARGET: ${selectedProd.name} (¥${selectedProd.original_price})`)

    const prompt = `你是秒杀活动策略专家。根据以下商品信息，生成最佳秒杀参数。

商品信息：
- 名称：${selectedProd.name}
- 原价：¥${selectedProd.original_price}
- 描述：${selectedProd.description || '无'}

请直接输出 JSON 格式（不要用 markdown 代码块），包含：
{
  "flash_price": 秒杀价格（数字，建议为原价的30%-70%），
  "total_stock": 秒杀库存（整数，根据商品热度建议10-200），
  "per_user_limit": 每人限购（整数，1-5），
  "duration_hours": 活动时长（整数，1-24小时），
  "reason": "简短解释定价策略（中文，20字内）"
}`

    addAILog('UPLINK: Sending to AI cluster...')
    const res = await sendChatMessage(`admin-flash-${Date.now()}`, prompt)

    if (res.code === 0 && res.data?.response) {
      addAILog('RECV: Response received, parsing...')
      const text = res.data.response
      const jsonMatch = text.match(/\{[\s\S]*\}/)

      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0])
        addAILog(`PARSE: flash_price=¥${parsed.flash_price}`)
        addAILog(`PARSE: stock=${parsed.total_stock}, limit=${parsed.per_user_limit}`)

        flashSaleForm.value.flash_price =
          Number(parsed.flash_price) || selectedProd.original_price * 0.5
        flashSaleForm.value.total_stock = Number(parsed.total_stock) || 50
        flashSaleForm.value.per_user_limit = Number(parsed.per_user_limit) || 1

        const durationHours = Number(parsed.duration_hours) || 1
        const now = new Date()
        now.setMinutes(now.getMinutes() + 5)
        flashSaleForm.value.start_time = new Date(now.getTime() - now.getTimezoneOffset() * 60000)
          .toISOString()
          .slice(0, 16)
        now.setHours(now.getHours() + durationHours)
        flashSaleForm.value.end_time = new Date(now.getTime() - now.getTimezoneOffset() * 60000)
          .toISOString()
          .slice(0, 16)

        addAILog(`DONE: ${parsed.reason || 'Optimization complete'}`)
        showMessage(parsed.reason || 'AI 优化完成', 'success')
      } else {
        throw new Error('AI 响应格式错误')
      }
    } else {
      throw new Error(res.message || 'AI 请求失败')
    }
  } catch (e: any) {
    addAILog(`ERROR: ${e.message}`)
    addAILog('FALLBACK: Using local algorithm...')
    showMessage(`AI 失败: ${e.message}`, 'error')
    flashSaleForm.value.flash_price = Math.round(selectedProd.original_price * 0.5 * 100) / 100
    flashSaleForm.value.total_stock = 50
    const now = new Date()
    now.setMinutes(now.getMinutes() + 5)
    flashSaleForm.value.start_time = new Date(now.getTime() - now.getTimezoneOffset() * 60000)
      .toISOString()
      .slice(0, 16)
    now.setHours(now.getHours() + 1)
    flashSaleForm.value.end_time = new Date(now.getTime() - now.getTimezoneOffset() * 60000)
      .toISOString()
      .slice(0, 16)
    addAILog('DONE: Fallback complete')
  } finally {
    generatingFlashAI.value = false
  }
}

const assetTypes = [
  { id: 'phone', label: 'Phone', icon: '📱' },
  { id: 'laptop', label: 'Laptop', icon: '💻' },
  { id: 'audio', label: 'Audio', icon: '🎧' },
  { id: 'box', label: 'Other', icon: '📦' },
]

const productForm = ref({
  name: '',
  description: '',
  original_price: 0,
  image_url: '',
})

const flashSaleForm = ref({
  product_id: 0,
  flash_price: 0,
  total_stock: 100,
  per_user_limit: 1,
  start_time: '',
  end_time: '',
})

const showMessage = (msg: string, type: 'success' | 'error') => {
  message.value = msg
  messageType.value = type
  setTimeout(() => (message.value = ''), 4000)
}

const handleImageUpload = async (event: Event) => {
  const input = event.target as HTMLInputElement
  if (input.files && input.files[0]) {
    const file = input.files[0]
    if (file.size > 5 * 1024 * 1024) {
      showMessage('Object too dense. Max 5MB allowed.', 'error')
      input.value = ''
      return
    }
    if (!file.type.startsWith('image/')) {
      showMessage('Only image files allowed.', 'error')
      input.value = ''
      return
    }
    uploadingImage.value = true
    try {
      const res = await uploadImage(file)
      if (res.code === 0) {
        productForm.value.image_url = res.data.url
        showMessage('Image uploaded successfully', 'success')
      } else {
        showMessage(res.message || 'Upload failed', 'error')
      }
    } catch (e: any) {
      showMessage(e.response?.data?.message || 'Upload failed', 'error')
    } finally {
      uploadingImage.value = false
      input.value = ''
    }
  }
}

const handleCreateProduct = async () => {
  if (!productForm.value.image_url) {
    showMessage('Visual asset required', 'error')
    return
  }
  loading.value = true
  try {
    const res = await createProduct(productForm.value)
    if (res.code === 0) {
      showMessage(`Registry Entry Created: ID ${res.data.id}`, 'success')
      flashSaleForm.value.product_id = res.data.id
      productForm.value = { name: '', description: '', original_price: 0, image_url: '' }
    } else {
      showMessage(res.message, 'error')
    }
  } catch (e: any) {
    showMessage(e.response?.data?.message || 'Uplink Failed', 'error')
  } finally {
    loading.value = false
  }
}

const fetchProducts = async () => {
  try {
    const res = await getProducts(1, 200)
    if (res.code === 0) products.value = res.data.products
  } catch {
    // Silent fail for product list
  }
}

watch(activeTab, (val) => {
  if (val === 'flash_sale') fetchProducts()
})

onMounted(() => fetchProducts())

const handleCreateFlashSale = async () => {
  loading.value = true
  try {
    const payload = {
      ...flashSaleForm.value,
      start_time: new Date(flashSaleForm.value.start_time).toISOString(),
      end_time: new Date(flashSaleForm.value.end_time).toISOString(),
    }
    const res = await createFlashSale(payload)
    if (res.code === 0) {
      showMessage(`Flash Event Synchronized: ID ${res.data.id}`, 'success')
    } else {
      showMessage(res.message, 'error')
    }
  } catch (e: any) {
    showMessage(e.response?.data?.message || 'Sync Failed', 'error')
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div
    class="min-h-screen pb-20 bg-background text-primary selection:bg-accent selection:text-white"
  >
    <div class="py-16 px-6 md:px-12 border-b border-white/5 mb-12 bg-black/40 backdrop-blur-md">
      <div class="container mx-auto">
        <div class="flex items-center gap-4 mb-4">
          <div class="w-2 h-8 bg-accent animate-pulse"></div>
          <h1 class="text-5xl md:text-6xl font-black tracking-tighter text-white uppercase">
            Merchant <span class="text-accent">Console</span>
          </h1>
        </div>
        <p class="text-secondary text-xs font-mono tracking-[0.4em] uppercase opacity-60">
          System Registry // Administrative Uplink v4.0.1
        </p>
      </div>
    </div>

    <div class="container mx-auto px-6 md:px-12 grid grid-cols-1 lg:grid-cols-4 gap-12">
      <div class="space-y-4">
        <button
          :class="[
            'w-full text-left px-6 py-4 text-xs font-black uppercase tracking-[0.2em] transition-all border flex items-center gap-4',
            activeTab === 'product'
              ? 'border-accent bg-accent/5 text-white shadow-[0_0_20px_rgba(227,53,53,0.2)]'
              : 'border-white/5 text-secondary hover:text-white hover:border-white/20',
          ]"
          @click="activeTab = 'product'"
        >
          <Package
            :class="['w-5 h-5', activeTab === 'product' ? 'text-accent' : 'text-tertiary']"
          />
          Asset Creation
        </button>
        <button
          :class="[
            'w-full text-left px-6 py-4 text-xs font-black uppercase tracking-[0.2em] transition-all border flex items-center gap-4',
            activeTab === 'flash_sale'
              ? 'border-accent bg-accent/5 text-white shadow-[0_0_20px_rgba(227,53,53,0.2)]'
              : 'border-white/5 text-secondary hover:text-white hover:border-white/20',
          ]"
          @click="activeTab = 'flash_sale'"
        >
          <Zap :class="['w-5 h-5', activeTab === 'flash_sale' ? 'text-accent' : 'text-tertiary']" />
          Event Sync
        </button>

        <div class="mt-20 p-6 bg-white/5 border border-white/5 rounded-sm">
          <div class="flex items-center gap-2 mb-4 text-accent">
            <BrainCircuit class="w-4 h-4" />
            <span class="text-[10px] font-black uppercase tracking-widest">AI Status</span>
          </div>
          <p class="text-[10px] text-tertiary leading-relaxed uppercase font-mono">
            Neural network standby. Ready to optimize metadata and event parameters.
          </p>
        </div>
      </div>

      <div class="lg:col-span-3">
        <transition name="fade" mode="out-in">
          <div
            v-if="message"
            :class="[
              'mb-8 p-5 text-xs font-mono font-bold tracking-widest border-l-4 shadow-xl',
              messageType === 'success'
                ? 'bg-green-500/10 text-green-400 border-green-500'
                : 'bg-red-500/10 text-red-400 border-red-500',
            ]"
          >
            [SYSTEM_LOG] > {{ message }}
          </div>
        </transition>

        <form
          v-if="activeTab === 'product'"
          class="space-y-8 bg-white/5 p-10 border border-white/5"
          @submit.prevent="handleCreateProduct"
        >
          <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div class="space-y-6">
              <div class="space-y-2">
                <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]"
                  >Entry Identity (Name)</label
                >
                <input
                  v-model="productForm.name"
                  type="text"
                  required
                  class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono text-sm tracking-tight"
                />
              </div>

              <div class="space-y-2">
                <div class="flex justify-between items-center">
                  <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]"
                    >Functional Specs</label
                  >
                  <button
                    type="button"
                    class="text-[10px] text-accent hover:text-white flex items-center gap-2 transition-all font-black uppercase tracking-widest"
                    :disabled="generatingAI"
                    @click="generateAIContent"
                  >
                    <Sparkles class="w-3 h-3" />
                    {{ generatingAI ? 'Processing...' : 'Neural Auto-Fill' }}
                  </button>
                </div>
                <textarea
                  v-model="productForm.description"
                  rows="4"
                  class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono text-xs leading-relaxed"
                ></textarea>
              </div>

              <div class="space-y-2">
                <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]"
                  >Original Value (¥)</label
                >
                <input
                  v-model.number="productForm.original_price"
                  type="number"
                  step="0.01"
                  required
                  class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono"
                />
              </div>
            </div>

            <div class="space-y-6">
              <div class="space-y-2">
                <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]"
                  >Visual Component</label
                >
                <div class="grid grid-cols-2 gap-2 mb-4">
                  <button
                    v-for="type in assetTypes"
                    :key="type.id"
                    type="button"
                    :class="[
                      'py-3 border text-[10px] font-black uppercase tracking-widest transition-all flex items-center justify-center gap-2',
                      productForm.image_url === `local:${type.id}`
                        ? 'bg-accent text-white border-accent'
                        : 'bg-black/40 border-white/10 text-tertiary hover:border-white/30',
                    ]"
                    @click="productForm.image_url = `local:${type.id}`"
                  >
                    <span>{{ type.icon }}</span> <span>{{ type.label }}</span>
                  </button>
                </div>

                <label class="block cursor-pointer group">
                  <div
                    class="flex flex-col items-center justify-center gap-3 py-10 border border-dashed border-white/10 group-hover:border-accent/50 transition-all bg-black/20"
                  >
                    <Upload
                      class="w-6 h-6 text-tertiary group-hover:text-accent transition-colors"
                    />
                    <span class="text-[10px] text-tertiary font-black uppercase tracking-widest"
                      >Uplink Raw Image</span
                    >
                  </div>
                  <input type="file" accept="image/*" class="hidden" @change="handleImageUpload" />
                </label>

                <div class="pt-4">
                  <input
                    v-model="productForm.image_url"
                    type="text"
                    placeholder="REMOTE_URL_HASH..."
                    class="w-full bg-black border border-white/10 px-4 py-3 text-white focus:border-accent outline-none font-mono text-[10px] tracking-tighter overflow-hidden"
                  />
                </div>
              </div>
            </div>
          </div>

          <button
            type="submit"
            :disabled="loading"
            class="w-full h-16 bg-white text-black font-black uppercase tracking-[0.3em] hover:bg-accent hover:text-white transition-all flex items-center justify-center gap-4 text-lg"
          >
            <Loader2 v-if="loading" class="w-6 h-6 animate-spin" />
            <Plus v-else class="w-6 h-6" />
            Commit to Registry
          </button>
        </form>

        <form
          v-if="activeTab === 'flash_sale'"
          class="space-y-8 bg-white/5 p-10 border border-white/5"
          @submit.prevent="handleCreateFlashSale"
        >
          <div class="space-y-6">
            <div class="space-y-2">
              <div class="flex justify-between items-center">
                <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]"
                  >Target Asset</label
                >
                <button
                  type="button"
                  class="text-[10px] text-accent hover:text-white flex items-center gap-2 transition-all font-black uppercase tracking-widest"
                  @click="fetchProducts"
                >
                  <RefreshCw class="w-3 h-3" /> Re-sync List
                </button>
              </div>
              <button
                type="button"
                class="w-full bg-black border border-white/10 px-5 py-4 text-left hover:border-accent/50 transition-all group"
                @click="showProductModal = true"
              >
                <div v-if="selectedProduct" class="flex items-center justify-between">
                  <span class="font-mono text-sm text-white">
                    ID:{{ selectedProduct.id }} // {{ selectedProduct.name }}
                  </span>
                  <span class="text-accent text-xs font-bold"
                    >¥{{ selectedProduct.original_price }}</span
                  >
                </div>
                <div v-else class="flex items-center justify-between text-tertiary">
                  <span class="font-mono text-sm">SELECT_TARGET_ASSET...</span>
                  <span class="text-accent text-xs">▼</span>
                </div>
              </button>
              <input type="hidden" :value="flashSaleForm.product_id" required />
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-8 items-start">
              <div class="space-y-6">
                <div class="space-y-2">
                  <div class="flex justify-between items-center">
                    <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]"
                      >Flash Value (¥)</label
                    >
                    <button
                      type="button"
                      class="text-[10px] text-accent hover:text-white flex items-center gap-2 transition-all font-black uppercase tracking-widest"
                      :disabled="generatingFlashAI"
                      @click="generateFlashAI"
                    >
                      <Sparkles class="w-3 h-3" /> Neural Optimization
                    </button>
                  </div>
                  <input
                    v-model.number="flashSaleForm.flash_price"
                    type="number"
                    step="0.01"
                    required
                    class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono"
                  />
                </div>
                <div class="space-y-2">
                  <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]"
                    >Unit Capacity</label
                  >
                  <input
                    v-model.number="flashSaleForm.total_stock"
                    type="number"
                    required
                    class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono"
                  />
                </div>
              </div>

              <div class="space-y-6">
                <div class="space-y-2">
                  <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]"
                    >Timeline Initial</label
                  >
                  <input
                    v-model="flashSaleForm.start_time"
                    type="datetime-local"
                    required
                    class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono text-sm"
                  />
                </div>
                <div class="space-y-2">
                  <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]"
                    >Timeline Termination</label
                  >
                  <input
                    v-model="flashSaleForm.end_time"
                    type="datetime-local"
                    required
                    class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono text-sm"
                  />
                </div>
              </div>
            </div>

            <div class="space-y-2">
              <label class="text-[10px] text-secondary uppercase font-black tracking-[0.3em]"
                >Entity Acquisition Limit</label
              >
              <input
                v-model.number="flashSaleForm.per_user_limit"
                type="number"
                min="1"
                required
                class="w-full bg-black border border-white/10 px-5 py-4 text-white focus:border-accent outline-none font-mono"
              />
            </div>

            <!-- AI 日志显示 -->
            <transition name="fade">
              <div
                v-if="generatingFlashAI || aiLogs.length > 0"
                class="mt-6 border border-white/10 bg-black/60 overflow-hidden"
              >
                <div class="flex items-center gap-3 px-4 py-2 border-b border-white/5 bg-white/5">
                  <div class="flex gap-1">
                    <span
                      class="w-2 h-2 rounded-full"
                      :class="generatingFlashAI ? 'bg-accent animate-pulse' : 'bg-green-500'"
                    ></span>
                    <span class="w-2 h-2 rounded-full bg-yellow-500/50"></span>
                    <span class="w-2 h-2 rounded-full bg-white/20"></span>
                  </div>
                  <span class="text-[9px] text-tertiary font-mono uppercase tracking-widest"
                    >Neural_Process_Log</span
                  >
                  <div v-if="generatingFlashAI" class="flex-1 h-1 bg-white/10 ml-4 overflow-hidden">
                    <div
                      class="h-full bg-accent animate-[progress_1.5s_ease-in-out_infinite]"
                    ></div>
                  </div>
                </div>
                <div class="p-3 max-h-32 overflow-y-auto font-mono text-[10px] leading-relaxed">
                  <div v-for="(log, i) in aiLogs" :key="i" class="text-tertiary">
                    <span class="text-accent/60">>&nbsp;</span>{{ log }}
                  </div>
                  <div v-if="generatingFlashAI" class="text-accent animate-pulse">
                    <span class="text-accent/60">>&nbsp;</span>Processing<span
                      class="animate-[blink_1s_infinite]"
                      >_</span
                    >
                  </div>
                </div>
              </div>
            </transition>
          </div>

          <button
            type="submit"
            :disabled="loading"
            class="w-full h-16 bg-accent text-white font-black uppercase tracking-[0.3em] hover:bg-white hover:text-black transition-all flex items-center justify-center gap-4 text-lg"
          >
            <Loader2 v-if="loading" class="w-6 h-6 animate-spin" />
            <Zap v-else class="w-6 h-6" />
            Synchronize Flash Event
          </button>
        </form>
      </div>
    </div>

    <!-- 商品选择弹窗 -->
    <teleport to="body">
      <transition name="fade">
        <div
          v-if="showProductModal"
          class="fixed inset-0 z-50 flex items-center justify-center p-4"
        >
          <div
            class="absolute inset-0 bg-black/80 backdrop-blur-sm"
            @click="showProductModal = false"
          ></div>
          <div
            class="relative w-full max-w-2xl max-h-[80vh] bg-surface border border-white/10 shadow-2xl flex flex-col"
          >
            <!-- 弹窗头部 -->
            <div class="flex items-center justify-between p-6 border-b border-white/5">
              <div>
                <h3 class="text-lg font-black text-white uppercase tracking-widest">
                  Select Target Asset
                </h3>
                <p class="text-[10px] text-tertiary font-mono mt-1">
                  {{ filteredProducts.length }} assets available
                </p>
              </div>
              <button
                class="p-2 hover:bg-white/10 transition-colors"
                @click="showProductModal = false"
              >
                <X class="w-5 h-5 text-secondary" />
              </button>
            </div>

            <!-- 搜索框 -->
            <div class="p-4 border-b border-white/5">
              <div class="relative">
                <Search class="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-tertiary" />
                <input
                  v-model="productSearchQuery"
                  type="text"
                  placeholder="SEARCH_BY_ID_OR_NAME..."
                  class="w-full bg-black border border-white/10 pl-12 pr-4 py-3 text-white focus:border-accent outline-none font-mono text-sm"
                />
              </div>
            </div>

            <!-- 商品列表 -->
            <div class="flex-1 overflow-y-auto p-2">
              <div
                v-if="filteredProducts.length === 0"
                class="p-8 text-center text-tertiary font-mono text-sm"
              >
                NO_MATCHING_ASSETS_FOUND
              </div>
              <button
                v-for="p in filteredProducts"
                :key="p.id"
                type="button"
                :class="[
                  'w-full px-4 py-3 text-left transition-all flex items-center justify-between gap-4 border-b border-white/5 last:border-0',
                  flashSaleForm.product_id === p.id
                    ? 'bg-accent/10 border-l-2 border-l-accent'
                    : 'hover:bg-white/5',
                ]"
                @click="selectProduct(p)"
              >
                <div class="flex-1 min-w-0">
                  <div class="flex items-center gap-3">
                    <span class="text-accent font-mono text-xs">ID:{{ p.id }}</span>
                    <span class="text-white font-medium truncate">{{ p.name }}</span>
                  </div>
                </div>
                <span class="text-secondary font-mono text-sm whitespace-nowrap"
                  >¥{{ p.original_price }}</span
                >
              </button>
            </div>
          </div>
        </div>
      </transition>
    </teleport>
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.4s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
input::-webkit-calendar-picker-indicator {
  filter: invert(1);
  cursor: pointer;
}

@keyframes progress {
  0% {
    width: 0%;
    margin-left: 0%;
  }
  50% {
    width: 30%;
    margin-left: 35%;
  }
  100% {
    width: 0%;
    margin-left: 100%;
  }
}

@keyframes blink {
  0%,
  50% {
    opacity: 1;
  }
  51%,
  100% {
    opacity: 0;
  }
}
</style>
